/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.43
 * Generated at: 2017-06-17 04:28:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import edu.spring.vo.BiddingVO;
import java.util.List;
import java.util.ArrayList;
import edu.spring.vo.ProductVO;

public final class biddingList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/product/footer.jsp", Long.valueOf(1497610153193L));
    _jspx_dependants.put("/WEB-INF/views/product/nav.jspf", Long.valueOf(1497576572836L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1496842997460L));
    _jspx_dependants.put("jar:file:/C:/Users/Summer/java_workspace/web_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Auction/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/product/header.jspf", Long.valueOf(1497671412104L));
    _jspx_dependants.put("jar:file:/C:/Users/Summer/java_workspace/web_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Auction/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("edu.spring.vo.ProductVO");
    _jspx_imports_classes.add("edu.spring.vo.BiddingVO");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("ul,li {\r\n");
      out.write("list-style:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("   .form-login{\r\n");
      out.write("      background:white;\r\n");
      out.write("      width:60%;\r\n");
      out.write("      padding:20px;\r\n");
      out.write("      margin:auto;  /*마진을 자동으로 줘서 가운데정렬됨(?)*/\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   .goodDetail_Area{margin:20px;width:500px;float:left; position:relative; top:200px; left:300px;}\r\n");
      out.write("\r\n");
      out.write("   .goodtitleArea{width:800px;border-bottom:1px solid #ddd;float:left;padding-bottom:5px; margin-bottom:10px; padding-left:15px;}\r\n");
      out.write("      .goods_tit_txt1{font-size: 19px;line-height: 21px; width:460px; font-family: Tahoma; font-weight: bold; }\r\n");
      out.write("      .goods_tit_txt1 a{color: #b56818;}\r\n");
      out.write("/*       .goods_tit_txt1 a:hover{text-decoration:underline;} */\r\n");
      out.write("      \r\n");
      out.write("   .goodGreadInfor{margin:20px;float:left;}\r\n");
      out.write("   .goodGreadInfor li{font-size:14px;color:#666;line-height: 16px;padding:4px 0; font-family: Tahoma;}\r\n");
      out.write("   .goodGreadInfor .strong{color:#000}\r\n");
      out.write("   .goodGreadInfor .deadtime{color:;}\r\n");
      out.write("   .goodGreadInfor .deadtimeShort{color:#e43137;}\r\n");
      out.write("   .goodGreadInfor .doogst{color:#e43137}\r\n");
      out.write("   .goodGreadInfor .pass{font-size: 12px;color:#888}\r\n");
      out.write("\r\n");
      out.write(".goodSeller{\r\n");
      out.write("   width:300px;display: inline-block; border-left:1px solid #ddd; padding:10px; margin-top:15px; position:absolute; top:200px; left:800px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".goodtitleArea2\r\n");
      out.write("   {border-bottom:1px solid #ddd;  float:left; width:100%;  padding-left:15px;}\r\n");
      out.write("\r\n");
      out.write(".goods_tit_txt2{font-size: 19px;line-height: 21px;margin:9px; width:460px; font-family: Tahoma; font-weight: bold;}\r\n");
      out.write("\r\n");
      out.write(".goodBidding{\r\n");
      out.write("   padding-left:45px; margin-top:10px;\r\n");
      out.write("}   \r\n");
      out.write("\r\n");
      out.write(".goodBidding td{font-size:14px;color:#666;  font-family: Tahoma;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write(".biddingTable{\r\n");
      out.write("text-align:left; width:500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".biddingTable tr th {\r\n");
      out.write("padding:2px; font-size:16px;color:#666;line-height: 16px;padding:4px 0; font-family: Tahoma; font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write(".biddingTable tr td{\r\n");
      out.write("padding:2px; font-size:14px;color:#666;line-height: 16px;padding:4px 0; font-family: Tahoma;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".remain_time{\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("    height: 16px;\r\n");
      out.write("    padding-bottom: 5px;\r\n");
      out.write("    padding-left: 17px;\r\n");
      out.write("    background: url(//pics.auction.co.kr/listing/used/2014/txt2_watch.gif) 0 3px no-repeat;\r\n");
      out.write("    font-family: Tahoma;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    color: #666666;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#div2{\r\n");
      out.write("   position:absolute;\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("  function onLoad() {\r\n");
      out.write("      div2.style.top  = parseInt(div1.style.top)+500;\r\n");
      out.write("  }\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 List<BiddingVO> list = new ArrayList<>();
   BiddingVO vo=new BiddingVO();
   vo.setUser_id("hoyoung");
   vo.setPrice(25000);
   vo.setRegdate(new Date());
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   list.add(vo);
   request.setAttribute("biddingList", list);
   
   
   
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/headerstyle1.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header id=\"top\">\r\n");
      out.write("<div id=\"hdWrap\">\r\n");
      out.write("   <div id=\"header\">\r\n");
      out.write("        <div class=\"util\">\r\n");
      out.write("            <div class=\"wrapper\">\r\n");
      out.write("                <ul>\r\n");
      out.write("               <li class=\"first\"><a href=\"/\"><img src=\"../resources/images/icon_home.png\" style=\"margin-top: 9px;\"></a></li>\r\n");
      out.write("               <li><a href=\"../user/login\">log-in</a></li>\r\n");
      out.write("               <li class=\"join\"><a href=\"../user/registerUser\">join us</a></li>\r\n");
      out.write("               <li><a href=\"../user/cart\">cart</a></li>\r\n");
      out.write("                    <li><a href=\"../user/cart\">order</a></li>\r\n");
      out.write("                    <li><a href=\"../user/myInfo\">my page</a></li>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"search\">               \r\n");
      out.write("                        <div class=\"sch\">\r\n");
      out.write("                            <form action=\"/shop/shopbrand.html\" method=\"post\" name=\"search\"><fieldset>\r\n");
      out.write("                                    <legend>상품 검색 폼</legend>\r\n");
      out.write("                                    <a href=\"javascript:search_submit();\"><input type=\"image\" src=\"../resources/images/btn_search_white.gif\" class=\"btn-sch\" alt=\"상품 검색\" title=\"상품 검색\" style=\"width:13px;\"></a>\r\n");
      out.write("                                    <input name=\"search\" onkeydown=\"CheckKey_search();\" value=\"\" class=\"MS_search_word keyword\">\r\n");
      out.write("                                </fieldset>\r\n");
      out.write("                             </form> \r\n");
      out.write("                        </div>\r\n");
      out.write("               </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <a href=\"/\"><img src=\"../resources/images/title.jpg\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("          ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/navstyle5.css\"/>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("<!-- ///  사이드 nav  /// -->\r\n");
      out.write("<nav>   \r\n");
      out.write("<div id=\"aside\">\r\n");
      out.write("   <div id=\"layer_cate\" class=\"aside_layer\" style=\"display: block; left: 0px;\">\r\n");
      out.write("      <div class=\"layer_inner\">\r\n");
      out.write("         <a href=\"\"><video src=\"../resources/images/left_love.mp4\" type=\"video/mp4\" autoplay=\"\" loop=\"\"></video></a>      \r\n");
      out.write("         <h3 class=\"title\">CATEGORY</h3>\r\n");
      out.write("         <ul class=\"list_cate\">\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=029&amp;type=P\">BEST 50</a></li>\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=019&amp;type=P\">NEW 5%DC</a></li>\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=016&amp;type=P\">당일배송</a></li>\r\n");
      out.write("            <li class=\"denim\"><a href=\"/shop/shopbrand.html?xcode=031&amp;type=P\">MOCO DENIM</a></li>\r\n");
      out.write("            <li class=\"made\"><a href=\"/shop/shopbrand.html?xcode=024&amp;type=P\">I LOVE MOCO</a></li>\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=033&amp;type=Y\">COUPLE LOOK</a></li>\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=036&amp;type=Y\">SUMMER</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("         <ul class=\"list_cate\">\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=009&amp;type=X\">OUTER</a></li>\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=005&amp;type=X\">TOP</a></li>\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=007&amp;type=O\">BLOUSE</a></li>\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=006&amp;type=O\">DRESS</a></li>\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=004&amp;type=X\">BOTTOM</a></li>\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=002&amp;type=X\">SHOES&amp;BAG</a></li>\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=023&amp;type=X\">ACCESSORY</a></li>\r\n");
      out.write("            <li><a href=\"/shop/shopbrand.html?xcode=030&amp;type=P\">SALE</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("      \r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>bidding history</h1>\r\n");
      out.write("\r\n");
      out.write("<section class=\"goodDetail_Area\">\r\n");
      out.write("\r\n");
      out.write("<ul class=\"goodtitleArea\">\r\n");
      out.write("    <li class=\"goods_tit_txt1\">입찰자수 : 0명 / 입찰건수 : 0건</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<form action=\"bidding\" method=\"post\">\r\n");
      out.write("<div id=\"div1\" style=\"position:relative; top:0px\">\r\n");
      out.write("<ul class=\"goodGreadInfor\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <table class=\"biddingTable\">    \r\n");
      out.write("            <tr>   \r\n");
      out.write("              <th>아이디</th>\r\n");
      out.write("               <th>수량</th>\r\n");
      out.write("               <th>가격</th>\r\n");
      out.write("               <th>작성시간</th>   \r\n");
      out.write("            </tr>\r\n");
      out.write("         \r\n");
      out.write("         ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         \r\n");
      out.write("         </table> \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"goodSeller\">\r\n");
      out.write("<ul class=\"goodtitleArea2\">\r\n");
      out.write("   <li class=\"goods_tit_txt2\">상품 정보</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<ul class=\"goodGreadInfor\">\r\n");
      out.write("   <li><img alt=\"파리saaass\" src=\"../resources/images/paris.jpg\"\r\n");
      out.write("            width=\"300px\" height=\"200px\" /></li>\r\n");
      out.write("   <li>상품 이름 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("   <li>상품 수량 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.quantity }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("   <li>입찰가 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.contract_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("   <li><span class=\"remain_time\">마감시간: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.closed_time }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<font id=\"id_left_time\">8일 15시간 27분 52초 남음</font></span></li>\r\n");
      out.write("   \r\n");
      out.write("<li>   \r\n");
      out.write("   <form>\r\n");
      out.write("      <table class=\"goodBidding\" >\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td><input style=\"height: 35px; margin-right:5px;width:220px\" \r\n");
      out.write("               type=\"text\" name=\"price\" placeholder=\"입찰 가격을 입력하세요\" /><input type=\"hidden\" name=\"product_code\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("            <td><img src=\"http://pics.auction.co.kr/listing/used/2014/btn_bidding.gif\" alt=\"\"></td>\r\n");
      out.write("            \r\n");
      out.write("          \r\n");
      out.write("            </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("   </form>\r\n");
      out.write("   \r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("   href=\"../resources/css/footer_style.css\" />\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("   <div class=\"footer_company\">\r\n");
      out.write("      <h2 class=\"hide\">회사정보</h2>\r\n");
      out.write("      <a class=\"company_logo\" href=\"\">특가대표! 세못동</a>\r\n");
      out.write("      <div class=\"company_info\">\r\n");
      out.write("         <dl>\r\n");
      out.write("            <dt class=\"hide\">회사명 :</dt>\r\n");
      out.write("            <dd>(주)위메프 (대표이사 : 세모동)</dd>\r\n");
      out.write("            <dt>주소 :</dt>\r\n");
      out.write("            <dd><address>서울특별시 강남구 영동대로 502 위메프빌딩</address></dd>\r\n");
      out.write("         </dl>\r\n");
      out.write("         <dl>\r\n");
      out.write("            <dt class=\"fst\">사업자등록번호 :</dt>\r\n");
      out.write("            <dd>120-87-55227</dd>\r\n");
      out.write("            <dt>통신판매업신고번호 :</dt>\r\n");
      out.write("            <dd>제 2010 서울 강남 02066호</dd>\r\n");
      out.write("         </dl>\r\n");
      out.write("         <dl>\r\n");
      out.write("            <dt class=\"fst\">관광사업등록번호 :</dt>\r\n");
      out.write("            <dd>제2010-000024호</dd>\r\n");
      out.write("            <dt>개인정보보호책임자 :</dt>\r\n");
      out.write("            <dd>세모동 (<a href=\"mailto:tec@wemakeprice.com\">tec@wemakeprice.com</a>)</dd>\r\n");
      out.write("         </dl>\r\n");
      out.write("         <p class=\"phone_number\">\r\n");
      out.write("            <span class=\"num_client\">\r\n");
      out.write("               고객센터 1588-4763, 평일 9:00~18:00, 주말/공휴일 10:00~17:00\r\n");
      out.write("               <a class=\"link_faq\" href=\"\">전화문의 전 클릭</a>\r\n");
      out.write("            </span>\r\n");
      out.write("            \r\n");
      out.write("         </p>\r\n");
      out.write("         <p class=\"copyright\">COPYRIGHT © WEMAKEPRICE INC.&nbsp; ALL RIGHTS RESERVED.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write(" </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var height = Number($('.goodDetail_Area').height());\r\n");
      out.write("if (height < 660) {\r\n");
      out.write("   height = 660;\r\n");
      out.write("}\r\n");
      out.write("$('#footer').css('position', 'relative');\r\n");
      out.write("$('#footer').css('top', (height + 250) + 'px');\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/product/biddingList.jsp(190,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/product/biddingList.jsp(190,9) '${ biddingList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ biddingList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/product/biddingList.jsp(190,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("vo");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            <tr>\r\n");
            out.write("                 <td><input type=\"hidden\" name=\"\" value=\"\"/>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                 <td><input type=\"hidden\" name=\"\" value=\"\"/>5개</td>\r\n");
            out.write("                 <td><input type=\"hidden\" name=\"\"value=\"\"/>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                 <td><input type=\"hidden\" name=\"\"value=\"\"/>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.regdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("             </tr>\r\n");
            out.write("         ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
