/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.43
 * Generated at: 2017-11-18 05:24:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/product/nav.jspf", Long.valueOf(1510504860659L));
    _jspx_dependants.put("jar:file:/C:/Study/lab_web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Auction/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1496842997460L));
    _jspx_dependants.put("/WEB-INF/views/product/header.jspf", Long.valueOf(1510982665573L));
    _jspx_dependants.put("jar:file:/C:/Study/lab_web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Auction/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <link rel=\"stylesheet\"\r\n");
      out.write("  href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" />\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/productListstyle2.css\"/> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<nav>: 링크, 메뉴\r\n");
      out.write(" -->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".wrapper {\r\n");
      out.write("/*    position: relative;\r\n");
      out.write("   overflow: auto; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper:after{\r\n");
      out.write("\tcontent:'';\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\tclear:both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  .main{\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        min-width: 1200px;\r\n");
      out.write("        height: 1000px;\r\n");
      out.write("        /*background-color:#ffa;*/\r\n");
      out.write("        /*\r\n");
      out.write("        찐주황:  #F15A22;\r\n");
      out.write("        연주황: #F58220\r\n");
      out.write("        하늘: #00ADF0\r\n");
      out.write("        */\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("#main {\r\n");
      out.write("   padding: 30px 5px;\r\n");
      out.write("   float:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".prdtop{\r\n");
      out.write("    font-size: 15px; \r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("     padding-left:30px;\r\n");
      out.write("     margin:5px;\r\n");
      out.write("    }\r\n");
      out.write(".p{\r\n");
      out.write("   padding-left:10px;\r\n");
      out.write("}       \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".prdul {\r\n");
      out.write("   list-style:none;\r\n");
      out.write("   padding:5px;\r\n");
      out.write("   }\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("   .prd {\r\n");
      out.write("        float : left;\r\n");
      out.write("      padding-left:20px;\r\n");
      out.write("      padding-top: 5px;\r\n");
      out.write("      margin:5px;\r\n");
      out.write("      width:300px; \r\n");
      out.write("      \r\n");
      out.write("     font-size: 13px;\r\n");
      out.write("     color: #565656;\r\n");
      out.write("     text-decoration:none;\r\n");
      out.write("     \r\n");
      out.write("     line-height: 20px;\r\n");
      out.write("     position: relative;\r\n");
      out.write("     \r\n");
      out.write("    }  \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   .item_sell{\r\n");
      out.write("      padding-top:5px;\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("      font-weight:bold;\r\n");
      out.write("   }\r\n");
      out.write("    .item_tit{\r\n");
      out.write("       \r\n");
      out.write("       height: 32px;\r\n");
      out.write("       margin-top: 13px;\r\n");
      out.write("       font-family: dotum;\r\n");
      out.write("       font-size: 12px;\r\n");
      out.write("       color: #333333;\r\n");
      out.write("       line-height: 17px;\r\n");
      out.write("   }  \r\n");
      out.write("   \r\n");
      out.write(" .productlist{\r\n");
      out.write("    background:white;\r\n");
      out.write("     width:950px;\r\n");
      out.write("       \r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .prdul:after{\r\n");
      out.write(" \tcontent:'';\r\n");
      out.write(" \tdisplay:block;\r\n");
      out.write(" \tclear:both;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(".remain_time{\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("    height: 14px;\r\n");
      out.write("    padding-bottom: 5px;\r\n");
      out.write("    padding-left: 17px;\r\n");
      out.write("    background: url(//pics.auction.co.kr/listing/used/2014/txt2_watch.gif) 0 3px no-repeat;\r\n");
      out.write("    font-family: Tahoma;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    color: #666666;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item_img {\r\n");
      out.write("   border: 5px solid white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon_auction{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 6px;\r\n");
      out.write("    right: -4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("   <link rel=\"stylesheet\"\r\n");
      out.write("  href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" />\r\n");
      out.write(" <style>\r\n");
      out.write("      .top1{\r\n");
      out.write("        background-color: #00ADF0;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("        padding-top: 10px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .top2{\r\n");
      out.write("        background-color: #F58220 ;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        padding-top: 5px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .top3{\r\n");
      out.write("        background-color: #F15A22;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .text{\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        /* 세로 가운데 정렬도 해야해 */\r\n");
      out.write("\r\n");
      out.write("        padding-left: 30px;\r\n");
      out.write("        padding-right: 30px;\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("      .breadcrumb{\r\n");
      out.write("        background-color: transparent;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        padding: 8px 15px;\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #tricycle{\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("        margin-left: 30px;\r\n");
      out.write("        margin-right: 0px; /*옆에 글씨 적으려고*/\r\n");
      out.write("        height:60px;\r\n");
      out.write("        vertical-align: top;\r\n");
      out.write("        border:0px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .breadcrumb2{\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("      }\r\n");
      out.write("      .breadcrumb2 li{\r\n");
      out.write("        float: left;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("      }\r\n");
      out.write("      .breadcrumb2:after{\r\n");
      out.write("        content:'';\r\n");
      out.write("        clear:both;\r\n");
      out.write("      }\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header id=\"top\">\r\n");
      out.write("\r\n");
      out.write(" <!-- <div class=\"top1\">\r\n");
      out.write("        <div class=\"text little\" >\r\n");
      out.write("          중고거래 가능한 옥션 장터입니다!\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div> -->\r\n");
      out.write("      <div class=\"top2\">\r\n");
      out.write("        <ul class=\"breadcrumb\">\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/user/login\">로그인</a></li>\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/user/registerUser\">회원가입</a></li>\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/user/cart\">장바구니</a></li>\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/product/registerProduct\">제품등록</a></li>\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/user/mypage\">마이옥션</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"top3\">\r\n");
      out.write("        <img id=\"tricycle\" src=\"http://localhost:8181\\auc\\resources\\images\\tricycle.png\" alt=\"세모동그라미\">\r\n");
      out.write("        <span class=\"text\"\r\n");
      out.write("          style=\"margin-left:0px; padding-left:0px; font-size:40px;\">UCTION  장터</span>\r\n");
      out.write("          <!--여기서 span에 margin-left 스타일 먹이면 왜 안먹을까 20px; 100px;등-->\r\n");
      out.write("          \r\n");
      out.write("         <ul class=\"breadcrumb2\">\r\n");
      out.write("          \r\n");
      out.write("          <li><h4><a class=\"text\" href=\"/auc/product/productList?category=fresh\" \r\n");
      out.write("          \t\t\tonmouseover=\"mouseover_header(this)\" onmouseout=\"mouseout_header(this)\">\r\n");
      out.write("            \t\t쌀/과일/농수축산물</a></h4></li>\r\n");
      out.write("          \r\n");
      out.write("          <li><h4><a class=\"text\" href=\"/auc/product/productList?category=drink\"\r\n");
      out.write("          \t\t\tonmouseover=\"mouseover_header(this)\" onmouseout=\"mouseout_header(this)\">\r\n");
      out.write("            \t\t커피/음료</a></h4></li>\r\n");
      out.write("          \r\n");
      out.write("          <li><h4><a class=\"text\" href=\"/auc/product/productList?category=healthy\"\r\n");
      out.write("         \t\t\tonmouseover=\"mouseover_header(this)\" onmouseout=\"mouseout_header(this)\">\r\n");
      out.write("            \t\t건강/다이어트</a></h4></li>\r\n");
      out.write("          \r\n");
      out.write("          <li><h4><a class=\"text\" href=\"/auc/product/productList?category=instant\" \r\n");
      out.write("          \t\t\tonmouseover=\"mouseover_header(this)\" onmouseout=\"mouseout_header(this)\">\r\n");
      out.write("           \t\t\t 즉석/가공식품</a></h4></li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    function mouseover_header(obj){\r\n");
      out.write("\r\n");
      out.write("      obj.style.color=\"#000\";\r\n");
      out.write("    }\r\n");
      out.write("    function mouseout_header(obj){\r\n");
      out.write("\r\n");
      out.write("      obj.style.color=\"#fff\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("        // 이렇게 하는게 안되는 이유!!\r\n");
      out.write("        // (넘나재밌는거) 등록된 onmouseover가 불렸을때 category[length]가 불려버림!없는 객체ㅇㅇ\r\n");
      out.write("\r\n");
      out.write("        // for(i=0;i<category.length;i++){\r\n");
      out.write("        //   category[i].onmouseover=\r\n");
      out.write("        //     function(){\r\n");
      out.write("        //       category[i].style.color=\"#000\";\r\n");
      out.write("        //     };\r\n");
      out.write("        //   category[i].onmouseout=\r\n");
      out.write("        //     function(){\r\n");
      out.write("        //       category[i].style.color=\"#fff\";\r\n");
      out.write("        //   };\r\n");
      out.write("        // }\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("      \r\n");
      out.write("          ");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>  -->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tnav{\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\tmargin:20px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#layer_cat{\r\n");
      out.write("\t\tborder : 1px solid #000;\r\n");
      out.write("\t\tpadding: 20px 5px 60px 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.title_cat{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tmargin:20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.list_cat{\r\n");
      out.write("\t\tlist-style: none;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.list_cat li{\r\n");
      out.write("\t\tmargin:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.list_cat li a{\r\n");
      out.write("\t\tcolor: #000;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("<!-- ///  사이드 nav  /// -->\r\n");
      out.write("<nav>\r\n");
      out.write("\r\n");
      out.write("   <div id=\"layer_cat\">\r\n");
      out.write("     \r\n");
      out.write("         <video src=\"../resources/images/Bread.mp4\" type=\"video/mp4\" width=\"210px\" autoplay=\"\" loop=\"\"></video> \r\n");
      out.write("         <h3 class=\"title_cat\">CATEGORY</h3>\r\n");
      out.write("         <ul class=\"list_cat\">\r\n");
      out.write("            <li><a href=\"/auc/product/productList?category=fresh\">쌀/과일/농수축산물</a></li>\r\n");
      out.write("            <li><a href=\"/auc/product/productList?category=drink\">커피/음료</a></li>\r\n");
      out.write("            <li><a href=\"/auc/product/productList?category=healthy\">건강/다이어트</a></li>\r\n");
      out.write("            <li><a href=\"/auc/product/productList?category=instant\">즉석/가공식품</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section id=\"main\">\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write(" <!-- 1,2,3일때 1줄(0)// 4,5,6일때 2줄(1) ...  -->\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tvar height = Number($('.logo').height());\r\n");
      out.write("\tvar height2 = (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lines}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("+1)*570;\r\n");
      out.write("\tconsole.log(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lines+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("+\"lines\");\r\n");
      out.write("\tif (height2 < 660) {\r\n");
      out.write("\t   height2 = 660;\r\n");
      out.write("\t}\r\n");
      out.write("\t$('#footer .footer_company').css('position', 'relative');\r\n");
      out.write("\t$('#footer').css('position', 'absolute');\r\n");
      out.write("\t$('#footer').css('top', (250+height2)+ 'px');\r\n");
      out.write("\t$('#footer').css('left', 0+ 'px');\r\n");
      out.write("\t$('#footer').css('margin', 0+'px');\r\n");
      out.write("\t//$('#footer').css('height',164+'px');\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tconsole.log(\"봐방\"+$('#img').attr('src'));\r\n");
      out.write("\t});\r\n");
      out.write("      \r\n");
      out.write("       function mouseOver(prd){\r\n");
      out.write("          //prd.style.background=\"black\"; \r\n");
      out.write("         // cursor:\"move\";\r\n");
      out.write("          \r\n");
      out.write("       }\r\n");
      out.write("   /*     function clickPrd(prd, product_code){\r\n");
      out.write("         \r\n");
      out.write("          \r\n");
      out.write("          prd.href='productDetail?code='+product_code;\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("       } */\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/product/productList.jsp(160,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("lines");
      // /WEB-INF/views/product/productList.jsp(160,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/product/productList.jsp(160,0) '${(productNum-1)/3 }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${(productNum-1)/3 }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/product/productList.jsp(162,0) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(0);
      // /WEB-INF/views/product/productList.jsp(162,0) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lines}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/views/product/productList.jsp(162,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("line_var");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write(" <!-- 0,1,2,3,4...(1번째줄에서 var은 0) -->\r\n");
            out.write("   \r\n");
            out.write("\r\n");
            out.write("   <div class=\"productlist\"><!-- div 1번째 줄  -->\r\n");
            out.write("\r\n");
            out.write("  \r\n");
            out.write("   <ul class=\"prdul\"> \r\n");
            out.write("    ");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("     \r\n");
            out.write("  </ul>\r\n");
            out.write("   \r\n");
            out.write(" </div> <!-- div 상품리스트 1번째 줄  -->\r\n");
            out.write(" \r\n");
            out.write(" ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/product/productList.jsp(169,4) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(0);
      // /WEB-INF/views/product/productList.jsp(169,4) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(2);
      // /WEB-INF/views/product/productList.jsp(169,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("order_var");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write(" <!-- 3개씩놓을꺼니까 0,1,2까지만.  -->\r\n");
            out.write("    ");
            if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("   \r\n");
            out.write("    ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("   ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/product/productList.jsp(170,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("product");
      // /WEB-INF/views/product/productList.jsp(170,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/product/productList.jsp(170,4) '${productList[(line_var*3)+order_var] }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${productList[(line_var*3)+order_var] }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/product/productList.jsp(172,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <li class=\"prd\" ><!--1번 째 상품입니다. -->\r\n");
          out.write("    <div onmouseover=\"mouseOver(this)\" style=\"display:inline-block\">\r\n");
          out.write("       <div class=\"item_img\">\r\n");
          out.write("       <a href=\"#\" class=\"prd\" onclick=\"clickPrd(this,");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\">\r\n");
          out.write("        <img alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" src=\"displayProductImg1?user_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.seller}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&product_code=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&index=0\" \r\n");
          out.write("        style=\"height:300px;width:300px;\" id=\"img\">    \r\n");
          out.write("         <img class=\"icon_auction\" alt=\"경매\" src=\"http://pics.auction.co.kr/listing/used/2014/icon_auc.png\">\r\n");
          out.write("         \r\n");
          out.write("        </a> \r\n");
          out.write("      </div>\r\n");
          out.write("      \r\n");
          out.write("     <!--  <div>\r\n");
          out.write("         <a href=\"\" onclick=\"\" >입찰하기</a>\r\n");
          out.write("         <a href=\"\" onclick=\"\" >구매하기</a>        \r\n");
          out.write("      </div> -->\r\n");
          out.write("     \r\n");
          out.write("      \r\n");
          out.write("            <div class=\"item_sell\">\r\n");
          out.write("            <a href=\"\" class=\"prdtop\"  style=\"color:#800000\" onclick=\"clickPrd(this,");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(')');
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("            <a href=\"productDetail?code=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"prd\" >\r\n");
          out.write("  \r\n");
          out.write("            <p class=\"p\">\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("              <span class=\"tit\">현재가</span> \r\n");
          out.write("              <span class=\"cost\"  style=\"margin:3px; text-indent: 10px; font-size:15px;\">\r\n");
          out.write("              \t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.contract_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("원 \r\n");
          out.write("              </span>\r\n");
          out.write("            </p>\r\n");
          out.write("         \r\n");
          out.write("             <p class=\"p\"><span>입찰수: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.bidders}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span></p>\r\n");
          out.write("             <p class=\"p\"><span class=\"remain_time\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.closed_time }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span></p>\r\n");
          out.write("            \r\n");
          out.write("            </a>\r\n");
          out.write("             \r\n");
          out.write("            <div><p class=\"p\"><a href=\"\" class=\"prd\" style=\"margin-bottom:5px; margin-left: 5px;\">즉시판매가 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.immediate_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" 원</a>\r\n");
          out.write("          </div>\r\n");
          out.write("          \r\n");
          out.write("          </div>\r\n");
          out.write("\r\n");
          out.write("      \r\n");
          out.write("      </div>\r\n");
          out.write("   </li><!-- 1번 째 상품입니다. -->\r\n");
          out.write("  \r\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/product/productList.jsp(195,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.contract_price==0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
