/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.43
 * Generated at: 2017-11-18 05:24:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Study/lab_web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Auction/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1496842997460L));
    _jspx_dependants.put("/WEB-INF/views/product/header.jspf", Long.valueOf(1510982665573L));
    _jspx_dependants.put("jar:file:/C:/Study/lab_web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Auction/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".wrapper:after{\r\n");
      out.write("\tcontent:'';\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\tclear:both;\r\n");
      out.write("}\r\n");
      out.write("      \r\n");
      out.write("#main {\r\n");
      out.write("   padding: 30px 5px;\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write(".goodTotal{\r\n");
      out.write("\t\r\n");
      out.write("\tmin-width: 1000px;\r\n");
      out.write("\tmargin:40px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".goodTotal:after{\r\n");
      out.write("\tcontent:'';\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\tclear:both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul{\r\n");
      out.write("\tlist-style:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write(".goodDetail_Area{margin:20px 30px 0 10px;width:470px;float:left;}\r\n");
      out.write("\r\n");
      out.write("   .goodtitleArea{width:500px;border-bottom:1px solid #ddd;float:left;padding-bottom:5px;}\r\n");
      out.write("      .goods_tit_txt1{font-size: 19px;line-height: 21px;margin-bottom: 0px; width:460px; color:#800000;}\r\n");
      out.write("      .goods_tit_txt1 a{color: #b56818;}\r\n");
      out.write("      .goods_tit_txt1 a:hover{text-decoration:underline;}\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("#goods_pic_main{\r\n");
      out.write("text-align:center;\r\n");
      out.write("vertical-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".goodImg_Area{ width:500px;float:left;}\r\n");
      out.write("   .goods_pic{width:500px; height:500px; border:solid 1px #ccc; display:block;position:relative; overflow:hidden;background:#fff}\r\n");
      out.write("   .goods_pic img{position:absolute;top:0;right:0;bottom:0;left:0;margin:auto;max-height:100%;max-width:100%;}\r\n");
      out.write("   .goods_pic_btn{width:100%; margin-top:20px; text-align:center;}\r\n");
      out.write("\r\n");
      out.write("   #s_goods{margin-top:10px; text-align:center;}\r\n");
      out.write("   .s_goods_pic{float:left; width:80px; height:80px; margin-left:5px; margin-right:5px; border:solid 1px #ccc; display:block; position:relative; overflow:hidden;}\r\n");
      out.write("   .s_goods_pic img{position:absolute;top:0;right:0;bottom:0;left:0;margin:auto;max-height:100%;max-width:100%;}\r\n");
      out.write("   .s_goods_pic_btn{float:left; margin-top:31px;}\r\n");
      out.write("   .thumImg{margin-top:10px; text-align:center;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".goodGreadInfor{margin:20px; float:left; width:100%; padding:0px;}\r\n");
      out.write("   .goodGreadInfor li{font-size:14px; fontcolor:#666;line-height: 16px;padding:4px 0; }\r\n");
      out.write("   .goodGreadInfor .strong{color:#000}\r\n");
      out.write("   .goodGreadInfor .deadtime{color:;}\r\n");
      out.write("   .goodGreadInfor .deadtimeShort{color:#e43137;}\r\n");
      out.write("   .goodGreadInfor .doogst{color:#e43137}\r\n");
      out.write("   .goodGreadInfor .pass{font-size: 12px;color:#888}\r\n");
      out.write("\r\n");
      out.write(".goodSeller{\r\n");
      out.write("   width:300px;display: inline-block; border-left:1px solid #ddd; padding:10px; top:10px; position:relative; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".goodtitleArea2\r\n");
      out.write("   {border-bottom:1px solid #ddd;  display: inline-block;padding-bottom:5px;width:100%}\r\n");
      out.write("\r\n");
      out.write(".goods_tit_txt2{font-size: 19px;line-height: 21px;margin-bottom: 0px; width:460px; color:#800000;}   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".star {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 75px;\r\n");
      out.write("    height: 13px;\r\n");
      out.write("    background: url(../resources/images/sp_star.gif) no-repeat 0 -37px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".star em {\r\n");
      out.write("\r\n");
      out.write("    display: block;\r\n");
      out.write("    background: url(../resources/images/sp_star.gif) no-repeat 0 -59px;\r\n");
      out.write("    text-indent: -9999px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".detailTitle {\r\n");
      out.write("    margin: 0 0 17px;\r\n");
      out.write("    border-bottom: 1px solid #e0e0e0;\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    line-height: 50px;\r\n");
      out.write("    letter-spacing: -0.5px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".detailDiv{\r\n");
      out.write(" \r\n");
      out.write("   width: 1000px;\r\n");
      out.write("   border: 1px solid #ccc;\r\n");
      out.write("   padding: 20px;\r\n");
      out.write("   margin: 30px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(".box{\r\n");
      out.write("   height: 350px;\r\n");
      out.write("   width: 700px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".detailFont{\r\n");
      out.write("   color:#f00;\r\n");
      out.write("   font-size: 120%;\r\n");
      out.write("         \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("   <link rel=\"stylesheet\"\r\n");
      out.write("  href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" />\r\n");
      out.write(" <style>\r\n");
      out.write("      .top1{\r\n");
      out.write("        background-color: #00ADF0;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("        padding-top: 10px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .top2{\r\n");
      out.write("        background-color: #F58220 ;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        padding-top: 5px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .top3{\r\n");
      out.write("        background-color: #F15A22;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .text{\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        /* 세로 가운데 정렬도 해야해 */\r\n");
      out.write("\r\n");
      out.write("        padding-left: 30px;\r\n");
      out.write("        padding-right: 30px;\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("      .breadcrumb{\r\n");
      out.write("        background-color: transparent;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        padding: 8px 15px;\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #tricycle{\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("        margin-left: 30px;\r\n");
      out.write("        margin-right: 0px; /*옆에 글씨 적으려고*/\r\n");
      out.write("        height:60px;\r\n");
      out.write("        vertical-align: top;\r\n");
      out.write("        border:0px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .breadcrumb2{\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("      }\r\n");
      out.write("      .breadcrumb2 li{\r\n");
      out.write("        float: left;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("      }\r\n");
      out.write("      .breadcrumb2:after{\r\n");
      out.write("        content:'';\r\n");
      out.write("        clear:both;\r\n");
      out.write("      }\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header id=\"top\">\r\n");
      out.write("\r\n");
      out.write(" <!-- <div class=\"top1\">\r\n");
      out.write("        <div class=\"text little\" >\r\n");
      out.write("          중고거래 가능한 옥션 장터입니다!\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div> -->\r\n");
      out.write("      <div class=\"top2\">\r\n");
      out.write("        <ul class=\"breadcrumb\">\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/user/login\">로그인</a></li>\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/user/registerUser\">회원가입</a></li>\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/user/cart\">장바구니</a></li>\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/product/registerProduct\">제품등록</a></li>\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/user/mypage\">마이옥션</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"top3\">\r\n");
      out.write("        <img id=\"tricycle\" src=\"http://localhost:8181\\auc\\resources\\images\\tricycle.png\" alt=\"세모동그라미\">\r\n");
      out.write("        <span class=\"text\"\r\n");
      out.write("          style=\"margin-left:0px; padding-left:0px; font-size:40px;\">UCTION  장터</span>\r\n");
      out.write("          <!--여기서 span에 margin-left 스타일 먹이면 왜 안먹을까 20px; 100px;등-->\r\n");
      out.write("          \r\n");
      out.write("         <ul class=\"breadcrumb2\">\r\n");
      out.write("          \r\n");
      out.write("          <li><h4><a class=\"text\" href=\"/auc/product/productList?category=fresh\" \r\n");
      out.write("          \t\t\tonmouseover=\"mouseover_header(this)\" onmouseout=\"mouseout_header(this)\">\r\n");
      out.write("            \t\t쌀/과일/농수축산물</a></h4></li>\r\n");
      out.write("          \r\n");
      out.write("          <li><h4><a class=\"text\" href=\"/auc/product/productList?category=drink\"\r\n");
      out.write("          \t\t\tonmouseover=\"mouseover_header(this)\" onmouseout=\"mouseout_header(this)\">\r\n");
      out.write("            \t\t커피/음료</a></h4></li>\r\n");
      out.write("          \r\n");
      out.write("          <li><h4><a class=\"text\" href=\"/auc/product/productList?category=healthy\"\r\n");
      out.write("         \t\t\tonmouseover=\"mouseover_header(this)\" onmouseout=\"mouseout_header(this)\">\r\n");
      out.write("            \t\t건강/다이어트</a></h4></li>\r\n");
      out.write("          \r\n");
      out.write("          <li><h4><a class=\"text\" href=\"/auc/product/productList?category=instant\" \r\n");
      out.write("          \t\t\tonmouseover=\"mouseover_header(this)\" onmouseout=\"mouseout_header(this)\">\r\n");
      out.write("           \t\t\t 즉석/가공식품</a></h4></li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    function mouseover_header(obj){\r\n");
      out.write("\r\n");
      out.write("      obj.style.color=\"#000\";\r\n");
      out.write("    }\r\n");
      out.write("    function mouseout_header(obj){\r\n");
      out.write("\r\n");
      out.write("      obj.style.color=\"#fff\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("        // 이렇게 하는게 안되는 이유!!\r\n");
      out.write("        // (넘나재밌는거) 등록된 onmouseover가 불렸을때 category[length]가 불려버림!없는 객체ㅇㅇ\r\n");
      out.write("\r\n");
      out.write("        // for(i=0;i<category.length;i++){\r\n");
      out.write("        //   category[i].onmouseover=\r\n");
      out.write("        //     function(){\r\n");
      out.write("        //       category[i].style.color=\"#000\";\r\n");
      out.write("        //     };\r\n");
      out.write("        //   category[i].onmouseout=\r\n");
      out.write("        //     function(){\r\n");
      out.write("        //       category[i].style.color=\"#fff\";\r\n");
      out.write("        //   };\r\n");
      out.write("        // }\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("    \t");
      out.write("\r\n");
      out.write("\t\t<section id=\"main\">\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("<div class=\"goodTotal\">\r\n");
      out.write("<div class=\"goodImg_Area\">\r\n");
      out.write("     <p class=\"goods_pic\" id=\"goods_pic_main\" style=\"position: relative;\">\r\n");
      out.write("     \t<img width=\"80%\" src=\"displayProductImg1?user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.seller}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&product_code=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&index=0\"  id=\"IMG_DETAIL\" name=\"IMG_DETAIL\" data-zoom-image=\"http://i.ebayimg.com/00/s/MTAwMFgxMDAw/z/l-4AAOSwGIRXYikX/$_1.JPG?set_id=880000500F\" onclick=\"viewFullImage();\" style=\"top: 50px; left: 50px;\">\r\n");
      out.write("     \t<img style=\"display: none; top: 50px; left: 50px;\" src=\"displayProductImg1?user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.seller}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&product_code=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&index=0\"  width=\"null\" height=\"null\">\r\n");
      out.write("     </p>\r\n");
      out.write("  <!-- 썸네일 이미지 -->\r\n");
      out.write("    <!-- todo : http://dev.ebay.auction.co.kr/?dir=shop&itemID=161747155826 -->\r\n");
      out.write("    <div class=\"thumImg\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tbody><tr>\r\n");
      out.write("                <td width=\"10\" align=\"left\"><img name=\"img_thumbnail_left\" src=\"http://pics3.wsbind.com/global/ns_lft01.png\" style=\"cursor: pointer;\"></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                \t<div style=\"width:460px;height:90px;overflow:hidden;border:red 1px none\" id=\"id_thumbnail_frame\">\r\n");
      out.write("                \t\t<table style=\"margin-left: 0px;\">\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                            \r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                  \r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        \t</tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                     </div>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td width=\"10\" align=\"right\">\r\n");
      out.write("                \t<img name=\"img_thumbnail_right\" src=\"http://pics3.wsbind.com/global/ns_right02.png\" style=\"cursor: pointer;\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </tbody></table>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"goodDetail_Area\">\r\n");
      out.write("\r\n");
      out.write("<ul class=\"goodtitleArea\">\r\n");
      out.write("    <li class=\"goods_tit_txt1\"><strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<ul class=\"goodGreadInfor\">\r\n");
      out.write(" ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   <li class= \"mainFont\"><strong>상품 코드:</strong> p_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("   <li class= \"mainFont\"><strong>상품 종류:</strong> ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(" </li>\r\n");
      out.write("    <li class= \"mainFont\"><div><strong>제품상태:</strong> <span class=\"detailFont\">상</span></div></li>\r\n");
      out.write("    <li class= \"mainFont\"><strong>상품 시작가 :</strong> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.start_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 원 </li>\r\n");
      out.write("    <li class= \"mainFont\"><strong>현재 입찰가 :</strong> <span class=\"detailFont\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.contract_price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>원</li>     \r\n");
      out.write("    <li class= \"mainFont\"><strong>남은 시간:</strong> <span id=\"lefttime\" class=\"detailFont\">종료된 경매입니다</span></li>\r\n");
      out.write("    <li class= \"mainFont\"><strong>판매종료:</strong> <span id=\"deadtime\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.closed_time }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("    <li class= \"mainFont\"><a href=\"\"><strong>입찰 수</strong> : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.bidders}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 명</a></li>  \r\n");
      out.write("    <li class= \"mainFont\">\r\n");
      out.write("    \t<input type=\"text\" style=\"height:33px\" placeholder=\"가격을 입력하세요\">\r\n");
      out.write("    \t<a id=\"\" href=\"\"><img src=\"http://pics.auction.co.kr/listing/used/2014/btn_bidding.gif\" alt=\"\"></a>\r\n");
      out.write("    \t&nbsp;\r\n");
      out.write("    \t<a id=\"\" href=\"\"><img src=\"http://pics.auction.co.kr/listing/used/2014/btn_buy.gif\" alt=\"\"></a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class= \"mainFont\">\r\n");
      out.write("    \t<a href=\"biddingList?code=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    \t\t<img src=\"../resources/images/history2.png\" height=\"30px;\" width=\"30px;\" alt=\"\">\r\n");
      out.write("    \t\t<button type=\"button\"  id=\"biddingList\" style=\"font-size:16px;\">\r\n");
      out.write("    \t\t\t<strong>입찰 기록</strong>\r\n");
      out.write("    \t\t</button>\r\n");
      out.write("    \t</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"goodSeller\">\r\n");
      out.write("<ul class=\"goodtitleArea2\">\r\n");
      out.write("   <li class=\"goods_tit_txt2\"><strong>판매자  정보</strong></li>\r\n");
      out.write("</ul>\r\n");
      out.write("<ul class=\"goodGreadInfor\">  \r\n");
      out.write("   <li><img src=\"../resources/images/seriouslytired.png\" style=\"width:150px; height:150px\"></li>\r\n");
      out.write("   <li>판매자 아이디 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.seller }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("   \r\n");
      out.write("   <li>판매자 별점/리뷰 :                      \r\n");
      out.write("                                <span class=\"star\"><em style=\"width:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${grade*100}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("%\">평점</em></span>\r\n");
      out.write("                                <span id=\"topPointTotalNumber\"><strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${grade }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong></span>\r\n");
      out.write("                                <span class=\"pointTotalPerson\">(참여 <em>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review_cnt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</em>)</span>\r\n");
      out.write("                            \r\n");
      out.write("   </li>\r\n");
      out.write("   <li><a id=\"\" href=\"\">판매자의 다른 상품들</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"detailDiv\">\r\n");
      out.write("   <h3 class=\"detailTitle\">상세정보</h3>\r\n");
      out.write("   <div class=\"box\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.detail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("   <h3 class=\"detailTitle\" >추가구성상품</h3>\r\n");
      out.write("   <div class=\"box\"></div>\r\n");
      out.write("   <h3 class=\"detailTitle\" >기  타</h3>\r\n");
      out.write("   <div class=\"box\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   </section> <!-- main(id)끝 -->\r\n");
      out.write("</div>\t\t<!-- wrapper(class)끝 -->\r\n");
      out.write("   \r\n");
      out.write("   ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   \r\n");
      out.write("\t  var year=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.closed_time.year}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("      var month=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.closed_time.month}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("+1;\r\n");
      out.write("      var date=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.closed_time.date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("      var hour=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.closed_time.hours}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("      var min=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.closed_time.minutes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("      \r\n");
      out.write("      var closed_time_ms= ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.closed_time.time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("      \r\n");
      out.write("      $('#deadtime').html(month+'월 '+date+'일 '+hour+'시 '+min+'분'); \r\n");
      out.write("      \r\n");
      out.write("      function countDown(){\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         var timeNow = new Date();\r\n");
      out.write("      \r\n");
      out.write("         var secLeft = (parseInt)((  closed_time_ms- timeNow.getTime()) /1000);\r\n");
      out.write("         var timerOver='N';\r\n");
      out.write("         \r\n");
      out.write("         if(secLeft <=0) {\r\n");
      out.write("            timerOver='Y';\r\n");
      out.write("         }else{\r\n");
      out.write("            $('#lefttime').html(secLeft+'초 남음'); \r\n");
      out.write("            console.log(secLeft+'초 남음');   \r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("         var minLeft =parseInt(secLeft/60);\r\n");
      out.write("         if(minLeft>=1){\r\n");
      out.write("            secLeft= secLeft-minLeft*60;      \r\n");
      out.write("            $('#lefttime').html(minLeft+'분 '+secLeft+'초 남음'); \r\n");
      out.write("         }\r\n");
      out.write("      \r\n");
      out.write("         \r\n");
      out.write("         var hourLeft = parseInt(minLeft/60);\r\n");
      out.write("         if(hourLeft >= 1){\r\n");
      out.write("            minLeft=minLeft-hourLeft*60;\r\n");
      out.write("            $('#lefttime').html(hourLeft+'시간 '+minLeft+'분 '+secLeft+'초 남음'); \r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("            var dayLeft = parseInt(hourLeft/24);\r\n");
      out.write("            if(dayLeft>=1){\r\n");
      out.write("               hourLeft = hourLeft- dayLeft*24;\r\n");
      out.write("               $('#lefttime').html(dayLeft+'일 '+hourLeft+'시간 '+minLeft+'분 '+secLeft+'초 남음'); \r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            if(timerOver='N'){\r\n");
      out.write("                setTimeout(\"countDown()\", 1000) ;\r\n");
      out.write("                console.log('countDown!');\r\n");
      out.write("            }\r\n");
      out.write("         \r\n");
      out.write("         }//function countDown()\r\n");
      out.write("      \r\n");
      out.write("      //카운트다운실행\r\n");
      out.write("      countDown();\r\n");
      out.write("      \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/product/productDetail.jsp(169,28) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fileNum-1 }", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/views/product/productDetail.jsp(169,28) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(0);
      // /WEB-INF/views/product/productDetail.jsp(169,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                             <td align=\"center\" height=\"90\">\r\n");
            out.write("                              <a href=\"#\" data-image=\"displayProductImg1?user_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.seller}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&product_code=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&index=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-zoom-image=\"displayProductImg1?user_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.seller}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&product_code=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&index=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                               <img src=\"displayProductImg1?user_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.seller}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&product_code=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&index=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"  onclick=\"document.getElementById('IMG_DETAIL').src='displayProductImg1?user_id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.seller}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&product_code=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&index=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'\" width=\"80\" height=\"80\" style=\"margin-top: 0px;\">\r\n");
            out.write("                              </a>\r\n");
            out.write("                             </td>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/product/productDetail.jsp(200,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/product/productDetail.jsp(200,1) '${product.category}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${product.category}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/product/productDetail.jsp(200,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cate");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/product/productDetail.jsp(202,49) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate=='fresh'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("쌀/과일/농수축산물");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/product/productDetail.jsp(203,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate=='drink'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("커피/음료");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/product/productDetail.jsp(204,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate=='healthy'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("건강/다이어트");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/product/productDetail.jsp(205,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate=='instant'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("즉석/가공식품");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
