/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.43
 * Generated at: 2017-06-18 21:32:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registerProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/gstyle1.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/gstyle2.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/gstyle3.css\"/>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\"/>\r\n");
      out.write("<title>판매 정보</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("<script src=\"//code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/ui/1.11.4/jquery-ui.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".file-drop{\r\n");
      out.write("   width: 593px;\r\n");
      out.write("   height: 200px;\r\n");
      out.write("   border: 1px solid grey;\r\n");
      out.write("   overflow:scroll;\r\n");
      out.write("   /* overflow-x:hidden; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".forImg{\r\n");
      out.write("\tborder:2px dotted grey; \r\n");
      out.write("\tborder-radius: 5px; \r\n");
      out.write("\tmargin:30px; \r\n");
      out.write("\theight:140px; \r\n");
      out.write("\twidth:140px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- /// 상품 등록시작 세션  /// -->\r\n");
      out.write("      <section class=\"login-section\">\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("            <div class=\"cont-title\"><!-- 타이틀 시작 -->\r\n");
      out.write("               <h2>상품 판매 등록</h2>\r\n");
      out.write("               <ul class=\"list-unstyled\">\r\n");
      out.write("                  <li><span class=\"list-icon-line\">-</span>아래 항목을 충실히 작성해 주세요. 공란이 있을 경우 상품등록을 할 수 없습니다..</li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div><!-- 타이틀 끝 -->\r\n");
      out.write("\r\n");
      out.write("             <form  action=\"registerProduct\" method=\"post\"><!-- 상품 판매 \"이름\" 시작  -->\r\n");
      out.write("               <div class=\"login-cont-all\">\r\n");
      out.write("                  <article class=\"login-cont\"><!-- article 시작 -->\r\n");
      out.write("                     <div class=\"block1\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <label for=\"user_id\" class=\"col-sm-2 control-label lable-title\">상품이름 &nbsp;<span style=\"color: red; font-weight:bold\">(*)</span></label>\r\n");
      out.write("                           <div class=\"col-sm-10\">\r\n");
      out.write("                              <input type=\"text\" class=\"form-control\" id=\"usrId\" name=\"name\" placeholder=\"상품이름을 입력하세요\"  required/>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div><!-- 상품 판매 \"이름\" 끝  -->\r\n");
      out.write("                     \r\n");
      out.write("              <!--        <div class=\"block1\">상품 \"코드\" 시작 \r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <label for=\"user_pw\" class=\"col-sm-2 control-label lable-title\">사진코드</label>\r\n");
      out.write("                           <div class=\"col-sm-9\">\r\n");
      out.write("                              <input type=\"text\" id=\"pswd\" name=\"pswd\" placeholder=\"코드 8자리 입력하세요\">\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>상품 판매 \"코드\" 끝 \r\n");
      out.write("                      -->\r\n");
      out.write("                      \r\n");
      out.write("                     <div class=\"block1\"><!-- 상품 판매 \"카테고리\" 시작 -->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <label for=\"user_pw\" class=\"col-sm-2 control-label lable-title\">카테고리 &nbsp;<span style=\"color: red; font-weight:bold\">(*)</span></label>\r\n");
      out.write("                           <div class=\"col-sm-10\">\r\n");
      out.write("                               <label for =\"category\"></label>   \r\n");
      out.write("                                    <select id = \"category\" name =\"category\">\r\n");
      out.write("                                       <option value=\"fresh\">쌀/과일/농수축산물</option>\r\n");
      out.write("                                       <option value=\"drink\">커피/음료</option>\r\n");
      out.write("                                       <option value=\"healthy\">건강/다이어트</option>\r\n");
      out.write("                                       <option value=\"instant\">즉석/가공식품</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                              \r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div><!-- 상품 판매 \"카테고리\" 끝  -->\r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"block1\"><!-- 상품 판매 \"수량\" 시작  -->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <label for=\"quantity\" class=\"col-sm-2 control-label lable-title\">수량 &nbsp;<span style=\"color: red; font-weight:bold\">(*)</span></label>\r\n");
      out.write("                           <div class=\"col-sm-10\">\r\n");
      out.write("                              <input type=\"text\" class=\"form-control\" id=\"pswd\" name=\"quantity\" placeholder=\"개수, 무게 등\" required>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div><!-- 상품 판매 \"수량\" 끝  -->\r\n");
      out.write("               \r\n");
      out.write("                     <div class=\"block1\"><!-- 상품 판매 \"사진\" 시작 -->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <label for=\"user_pw\" class=\"col-sm-2 control-label lable-title\">상품 사진 등록 &nbsp;<span style=\"color: red; font-weight:bold\">(*)</span></label>\r\n");
      out.write("                           <div class=\"col-sm-8\">\r\n");
      out.write("                              \r\n");
      out.write("                      <!-- Ajax를 이용한 파일 업로드 -->\r\n");
      out.write("                            <div class=\"form-control file-drop\" id=\"pswd\">\r\n");
      out.write("                            \r\n");
      out.write("                            \t<div class=\"forImg picImg\" >\r\n");
      out.write("                            \t\t<!-- 사진검색 우측 하단 버튼 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img alt=\"사진 등록\"  src=\"../resources/images/pic.png\" width=\"50px\" style=\"margin:43px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <div class=\"forImg\">\r\n");
      out.write("                            \t\t<img alt=\"한결\" src=\"../resources/images/paris.jpg\" width=\"137px\" height=\"137px\" >\r\n");
      out.write("                            \t</div> -->\r\n");
      out.write("                            \r\n");
      out.write("                            </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div><!-- 상품 판매 \"사진\" 끝  -->\r\n");
      out.write("                     <div id=\"di\"></div>\r\n");
      out.write("                     \r\n");
      out.write("                   \r\n");
      out.write("                   <div class=\"block1\"><!-- 상품 판매 \"시작가\" 시작  -->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <label for=\"start_price\" class=\"col-sm-2 control-label lable-title\">시작가 &nbsp;<span style=\"color: red; font-weight:bold\">(*)</span></label>\r\n");
      out.write("                           <div class=\"col-sm-10\">\r\n");
      out.write("                              <input type=\"text\" class=\"form-control\" id=\"pswd\" name=\"start_price\" placeholder=\"입찰 시작 가격을 입력하세요.\" required>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div><!-- 상품 판매 \"시작가\" 끝  -->\r\n");
      out.write("                     \r\n");
      out.write("                   \r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"block1\"><!-- 상품 판매 \"즉시판매가\" 시작  -->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <label for=\"user_pw\" class=\"col-sm-2 control-label lable-title\">즉시판매가 &nbsp;<span style=\"color: red; font-weight:bold\">(*)</span></label>\r\n");
      out.write("                           <div class=\"col-sm-10\">\r\n");
      out.write("                              <input type=\"text\" class=\"form-control\" id=\"pswd\" name=\"immediate_price\" placeholder=\"즉시판매 가격을 입력하세요.\" required>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div><!-- 상품 판매 \"즉시판매가\" 끝  -->\r\n");
      out.write("                     \r\n");
      out.write("                     \r\n");
      out.write("                    <div class=\"block1\"><!-- 상품 판매 \"입찰시작시간\" 시작  -->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <label for=\"\" class=\"col-sm-2 control-label lable-title\">입찰시작시간</label>\r\n");
      out.write("                           <div class=\"col-sm-10\">\r\n");
      out.write("                              <input type=\"datetime-local\" id=\"pswd\" name=\"\" placeholder=\"입찰 시작 시간 입력. 공란일 경우 상품등록과 함께 입찰 시작\">\r\n");
      out.write("                           </div>\r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div><!-- 상품 판매 \"제품등록날짜\" 끝  -->\r\n");
      out.write("                     \r\n");
      out.write("                     \r\n");
      out.write("                     <div class=\"block1\"><!-- 상품 판매 \"마감날짜\" 시작  -->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <label for=\"closed_time\" class=\"col-sm-2 control-label lable-title\">입찰마감시간</label>\r\n");
      out.write("                           <div class=\"col-sm-10\">\r\n");
      out.write("                              <input type=\"datetime-local\" id=\"pswd\" name=\"dead_line\" placeholder=\"입찰 마감 시간 입력\">\r\n");
      out.write("                              \t<!-- 원래 closed_time으로 넘겨주는데 그렇게하면 못받아들임 Date타입 property에 set을 못함  ㅉㅉ-->\r\n");
      out.write("                           </div>\r\n");
      out.write("                           \r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div><!-- 상품 판매 \"마감날짜\" 끝  -->            \r\n");
      out.write("                  \r\n");
      out.write("             \r\n");
      out.write("                     \r\n");
      out.write("                      <div class=\"block1\"><!-- 상품 판매 \"상세정보\" 시작  -->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <label for=\"user_pw\" class=\"col-sm-2 control-label lable-title\">상세정보</label>\r\n");
      out.write("                           <div class=\"col-sm-10\">\r\n");
      out.write("                              <textarea  id=\"pswd\" name=\"detail\" placeholder=\"상품의 상태, 상품의 출처 등(200자 미만)\" style=\"width:600px; height:250px\"></textarea>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div><!-- 상품 판매 \"상세정보\" 끝  -->      \r\n");
      out.write("                     \r\n");
      out.write("                       \r\n");
      out.write("                  </article><!-- article 끝 -->\r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               <div class=\"btn-area\"><!-- 등록하기 버튼 -->\r\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-primary btn-block btn-login\" id=\"login_btn\">등록하기</button>\r\n");
      out.write("               </div><!-- 등록하기 버튼  요까이~ -->\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               <input type=\"hidden\" name=\"img\" id=\"img\" />\r\n");
      out.write("            </form>\r\n");
      out.write("            </div>\r\n");
      out.write("      </section>\r\n");
      out.write("         \r\n");
      out.write("      <!-- /// 상품 등록 세션 끝 /// -->\r\n");
      out.write("      \r\n");
      out.write(" \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("// 그림올라오면 효과주기\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" $(document).ready(function(){\r\n");
      out.write("\t \r\n");
      out.write("\t\tvar picImg=$('.picImg');\r\n");
      out.write("\t\t$('.picImg').on('dragenter mouseenter', function() {\r\n");
      out.write("\t\t\tpicImg.css('border','3px dotted blue');\r\n");
      out.write("\t    });\r\n");
      out.write("\t\t$('.picImg').on('mouseout dragleave', function() {\r\n");
      out.write("\t\t\tpicImg.css('border','2px dotted grey');\r\n");
      out.write("\t    });\r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("    // 파일을 끌어다 놓을 때 (drag & drop)\r\n");
      out.write("    // 브라우저가 파일을 자동으로 열어주는 기능을 막음 (기본적으로 브라우저가 동작을 한다.)\r\n");
      out.write("     \r\n");
      out.write("    $('.file-drop').on('dragenter dragover', function(event) {\r\n");
      out.write("       event.preventDefault();       \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    //drop 부분에서 한 가지 동작을 더 추가할 것이다. ajax 방식으로 파일을 업로드 하는 기능까지 추가!\r\n");
      out.write("    $('.file-drop').on('drop', function(event){\r\n");
      out.write("       \r\n");
      out.write("       // drop 이벤트의 기본 동작을 막음\r\n");
      out.write("       event.preventDefault();\r\n");
      out.write("       \r\n");
      out.write("       // Ajax를 이용해서 서버로 파일을 업로드\r\n");
      out.write("       // multipart/form-data 타입으로 파일을 업로드하기 위해서 \r\n");
      out.write("       var formData = new FormData();\r\n");
      out.write("       \r\n");
      out.write("       // drop한 파일들에 대한 정보 가져오기.\r\n");
      out.write("       var files = event.originalEvent.dataTransfer.files;  //event라는객체내에 originalEvent객체내에 dataTranfer객체내에 files라는 배열객체..?\r\n");
      out.write("       var i = 0;\r\n");
      out.write("       for (i = 0; i < files.length; i++){\r\n");
      out.write("          console.log(\"잉->\"+files[i]);\r\n");
      out.write("          console.log(\"잉2->\"+files[i].originalFileName);\r\n");
      out.write("       \r\n");
      out.write("          // 이제 이 파일 정보들을 formData에 넣는다. 서버에 보내기 위해서임.\r\n");
      out.write("          // 'files' 라는 이름으로 모든 파일들을 append 하기 \r\n");
      out.write("         formData.append('files', files[i]);\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          // formData가 완성이 되었으니, 서버로 보내기.\r\n");
      out.write("          // 제이쿼리 라이브러리가 포함되어있어야 $ 포함된 함수 쓸 수 있음! 에이작스!\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          $.ajax({\r\n");
      out.write("             type: 'post',\r\n");
      out.write("             url: '/auc/upload-ajax',\r\n");
      out.write("             data: formData, \r\n");
      out.write("             dataType: 'text',\r\n");
      out.write("             processData: false,\r\n");
      out.write("             contentType: false,\r\n");
      out.write("             /* \r\n");
      out.write("             form의 enctype 속성을 기본값인 \"application/x-www-form-urlencoded\"을 사용하지 않고,\r\n");
      out.write("             \"multipart/form-data\"를 사용하기 위해서 반드시 주어야 할 속성은\r\n");
      out.write("             dataType: text, processData, contentType: false\r\n");
      out.write("             \r\n");
      out.write("             processType: true이면 enctype이 기본값이 되기 때문에 반드시 false라고 주어야 한다.\r\n");
      out.write("             */\r\n");
      out.write("             success: function(data){\r\n");
      out.write("                //alert(data);\r\n");
      out.write("                \r\n");
      out.write("                var str = $('.file-drop').html(); //이렇게 하면 파일이 밑에 계속 추가될 것.\r\n");
      out.write("                str += '<div class=\"forImg\">' \r\n");
      out.write("                      + '<img src= \"http://localhost:8181/auc/display?fileName='\r\n");
      out.write("                      + data\r\n");
      out.write("                      + ' \" width=\"136px\" height=\"136px\"/>'\r\n");
      out.write("                      + '</div>';\r\n");
      out.write("                $('.file-drop').html(str);     \r\n");
      out.write("                \r\n");
      out.write("              \t\t\t\t\r\n");
      out.write("                var img=$('#img').val();\r\n");
      out.write("                console.log(\"value: \"+img);\r\n");
      out.write("                var filename=data.substring(data.lastIndexOf(\"/s_\") + 3);  // /s_이후의 묹자열=filename 받아오기\r\n");
      out.write("                console.log(\"filename->\"+filename);\r\n");
      out.write("                img= img+\"=\"+filename;\r\n");
      out.write("                $('#img').val(img);\r\n");
      out.write("\t \t\t\t\t\t\t \t\t\t\t\t\r\n");
      out.write("                                         \r\n");
      out.write("             } //end success\r\n");
      out.write("          }); //end ajax\r\n");
      out.write("          \r\n");
      out.write("       }//end for(i)\r\n");
      out.write("        \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write(" });\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
