/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.42
 * Generated at: 2017-06-12 11:53:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class starSelector_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/view.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery CDN 포함: 라이브러리 포함  -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* li #topStar10Select {\r\n");
      out.write("background-image: url(\"http://i1275.photobucket.com/albums/y443/Behseini/lister_zps15367983.png\") !important;\r\n");
      out.write("background-repeat: no-repeat;\r\n");
      out.write("background-position: 5px 7px;\r\n");
      out.write("width: 60px;\r\n");
      out.write("height: 25px;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("/* li {\r\n");
      out.write("\tdisplay: inline-table;\r\n");
      out.write("} */\r\n");
      out.write("</style>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"vote_lst\">\r\n");
      out.write("                    \t<dl class=\"lt\">\r\n");
      out.write("                \r\n");
      out.write("                        <dt id=\"topStarLabel\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/detail/txt_point_click.gif\" width=\"38\" height=\"11\" class=\"starscore_guide_txt\" alt=\"별점주기\"></dt>\r\n");
      out.write("                        <dd id=\"topStarSelectbox\">\r\n");
      out.write("                            <div class=\"pointSelect fl\" >\r\n");
      out.write("                                <a onclick=\"clickSelector()\" href=\"#\" class=\"default\" id=\"starScoreMenu_1\"><span class=\"star_type4\"><span id=\"topTargetMask\" class=\"mask\" style=\"width:100%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"점수선택\" class=\"starscore_star_pic\" ></span></span></a>\r\n");
      out.write("                                <ul style=\"display:none\" id=\"pointSelectOption\">\r\n");
      out.write("                                <li><a onclick=\"clickcr(this,'bdt.star','','10',event)\" href=\"#\" id=\"topStar10Select\" title=\"10점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:100%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"10점\">10점</span></span></a></li>\r\n");
      out.write("                                <li><a onclick=\"clickcr(this,'bdt.star','','9',event)\" href=\"#\" id=\"topStar9Select\" title=\"9점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:90%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"9점\">9점</span></span></a></li>\r\n");
      out.write("                                <li><a onclick=\"clickcr(this,'bdt.star','','8',event)\" href=\"#\" id=\"topStar8Select\" title=\"8점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:80%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"8점\">8점</span></span></a></li>\r\n");
      out.write("                                <li><a onclick=\"clickcr(this,'bdt.star','','7',event)\" href=\"#\" id=\"topStar7Select\" title=\"7점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:70%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"7점\">7점</span></span></a></li>\r\n");
      out.write("                                <li><a onclick=\"clickcr(this,'bdt.star','','6',event)\" href=\"#\" id=\"topStar6Select\" title=\"6점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:60%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"6점\">6점</span></span></a></li>\r\n");
      out.write("                                <li><a onclick=\"clickcr(this,'bdt.star','','5',event)\" href=\"#\" id=\"topStar5Select\" title=\"5점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:50%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"5점\">5점</span></span></a></li>\r\n");
      out.write("                                <li><a onclick=\"clickcr(this,'bdt.star','','4',event)\" href=\"#\" id=\"topStar4Select\" title=\"4점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:40%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"4점\">4점</span></span></a></li>\r\n");
      out.write("                                <li><a onclick=\"clickcr(this,'bdt.star','','3',event)\" href=\"#\" id=\"topStar3Select\" title=\"3점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:30%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"3점\">3점</span></span></a></li>\r\n");
      out.write("                                <li><a onclick=\"clickcr(this,'bdt.star','','2',event)\" href=\"#\" id=\"topStar2Select\" title=\"2점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:20%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"2점\">2점</span></span></a></li>\r\n");
      out.write("                                <li><a onclick=\"clickcr(this,'bdt.star','','1',event)\" href=\"#\" id=\"topStar1Select\" title=\"1점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:10%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"1점\">1점</span></span></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"#\" class=\"btn_bx fl\" id=\"topStarScoreSubmitButton\" onclick=\"clickcr(this,'bdt.starok','','',event);\"  ><span>확인</span></a>\r\n");
      out.write("                    \t</dd>\r\n");
      out.write("                    \t<dd id=\"topStarText\" class=\"txt\" style=\"display:none;\"><span>참여하셨습니다.</span></dd>\r\n");
      out.write("                    \t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("                        </dl>\r\n");
      out.write("                   \r\n");
      out.write("                    </div>\r\n");
      out.write("      \r\n");
      out.write("      <script>\r\n");
      out.write("  \r\n");
      out.write("      \t\t\r\n");
      out.write("      \t\tfunction clickSelector(){\r\n");
      out.write("      \t\t\tvar display = $('#pointSelectOption').css('display');\r\n");
      out.write("      \t\t\t\r\n");
      out.write("      \t\t\tif(display=='none'){\r\n");
      out.write("      \t\t\t\t$('#pointSelectOption').css('display','inline-table');\r\n");
      out.write("      \t\t\t}\r\n");
      out.write("      \t\t\telse {\r\n");
      out.write("      \t\t\t\t$('#pointSelectOption').css('display','none');\r\n");
      out.write("      \t\t\t}\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t\t\r\n");
      out.write("\r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
