/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.43
 * Generated at: 2017-06-19 04:55:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("#a{\r\n");
      out.write("border: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".s1, .s2 {\r\n");
      out.write("   width: 10px;\r\n");
      out.write("   height: 60px;\r\n");
      out.write("}\r\n");
      out.write(".s3, .s4 {\r\n");
      out.write("   width: 10px;\r\n");
      out.write("   height: 60px;\r\n");
      out.write("}\r\n");
      out.write("#a {\r\n");
      out.write("    border: 1px solid #964b4b;\r\n");
      out.write("    background: #964b4b; \r\n");
      out.write("}\r\n");
      out.write(".sub_title_dep{\r\n");
      out.write("   image-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contents{\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menu {\r\n");
      out.write("   list-style-type: none;\r\n");
      out.write("}\r\n");
      out.write("/* 부모요소 자식요소 */\r\n");
      out.write("#menu li {\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   margin-left: 50px;\r\n");
      out.write("   width: 500px;\r\n");
      out.write("   height: 150px;\r\n");
      out.write("   text-align: left;\r\n");
      out.write("   background: white;\r\n");
      out.write("   color: darkgrey;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("/* #menu li:hover {\r\n");
      out.write("   background: lightpink;\r\n");
      out.write("}\r\n");
      out.write("#menu li:active {\r\n");
      out.write("   background: green;\r\n");
      out.write("   color: red;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" .sub_title_dep{\r\n");
      out.write("float: left;\r\n");
      out.write("position: relative;\r\n");
      out.write("left: 40%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contents {\r\n");
      out.write("\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("position: relative;\r\n");
      out.write("left: 20%\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"contents\" >\r\n");
      out.write("            \r\n");
      out.write("   <div class=\"s1\"></div>\r\n");
      out.write("   <div class=\"sub_title_dep\"><img src=\"../resources/images/title_mypage.gif\" alt=\"상단 타이틀\" width=\"140%\" style=\"margin:0px\"></div>\r\n");
      out.write("   <div class=\"s2\"></div>\r\n");
      out.write("   <hr/>\r\n");
      out.write("\r\n");
      out.write("   <ul id=\"menu\">\r\n");
      out.write("      <a href=\"cart\"><li><br/><spen id=\"a\"><b> 장바구니 </b></spen><br/><br/><h5>고객님께서 낙찰 받으신 상품이 담겨있습니다.<br/><br/>상품선택후 구매하기 버튼으로 결제를 하시면 상품배송이 시작됩니다.</h5></li></a>\r\n");
      out.write("      <a href=\"myInfo\"><li><br/><spen id=\"a\"><b> 회원 정보 </b></spen><br/><br/><h5>고객님의 개인정보를 관리하는 공간입니다.<br/><br/>개인정보를 최신 정보로 유지하시면 보다 간편히 경매를 즐기실 수 있습니다.</h5></li></a>\r\n");
      out.write("   </ul>\r\n");
      out.write("   <div class=\"s3\"></div>\r\n");
      out.write("   \r\n");
      out.write("   <ul id=\"menu\">\r\n");
      out.write("      <a href=\"biddingList\"><li><br/><spen><b id=\"a\"> 입찰 목록  </b></spen><br/><br/><h5>고객님께서 입찰하신 목록을 한눈에 살펴볼 수 있어요.<br/><br/>현재 진행중인 경매에 입찰중인 상품들을 볼 수 있습니다.</h5></li></a>\r\n");
      out.write("      <a href=\"buyList\"><li><br/><spen><b id=\"a\"> 구매 목록  </b></spen><br/><br/><h5>고객님께서 작성하신 게시물을 한눈에 관리하실 수 있습니다 살펴볼 수 있어요.<br/><br/>구매가 완료된 상품들은 상품평을 작성하실 수 있습니다.</h5></li></a>\r\n");
      out.write("   </ul>\r\n");
      out.write("   <div class=\"s4\"></div>\r\n");
      out.write("   \r\n");
      out.write("   <ul id=\"menu\">\r\n");
      out.write("      <a href=\"../product/registerProduct\"><li><br/><spen><b id=\"a\"> 상품 등록  </b></spen><br/><br/><h5>고객님께서 경매에 상품을 등록하실 수 있습니다.</h5></li></a>\r\n");
      out.write("      <a href=\"productList\"><li><br/><spen><b id=\"a\"> 내 상품 보기  </b></spen><br/><br/><h5>고객님께서 경매에 등록하신 상품들을  관리하실 수 있습니다.</h5></li></a>\r\n");
      out.write("   </ul>\r\n");
      out.write("   <div class=\"s4\"></div>\r\n");
      out.write("      \r\n");
      out.write("   <ul id=\"menu\">\r\n");
      out.write("      <a href=\"#none\"><li><br/><spen><b id=\"a\"> 관심 상품 </b></spen><br/><br/><h5>고객님께서 관심상품으로 등록한 상품들을 한눈에 살펴볼 수 있습니다.</h5></li></a>\r\n");
      out.write("      <a href=\"registerReview\"><li><br/><spen><b id=\"a\"> 마이 리뷰 </b></spen><br/><br/><h5>고객님께서 작성하신 게시물을 한눈에 살펴볼 수 있습니다.</h5></li></a>\r\n");
      out.write("   </ul>\r\n");
      out.write("   <div class=\"s4\"></div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
