/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.42
 * Generated at: 2017-06-13 11:36:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registerReview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/common1.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/view1.css\">\r\n");
      out.write("<title>판매자 평점 등록</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("   #table, #table thead{\r\n");
      out.write("      border: 2px solid grey;\r\n");
      out.write("      padding: 5px;\r\n");
      out.write("   }\r\n");
      out.write("   #table tr, #table tr td{\r\n");
      out.write("      margin:5px;   \r\n");
      out.write("      padding:5px;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("   <h1>상품평</h1>\r\n");
      out.write("   \r\n");
      out.write("   <table id=\"table\">\r\n");
      out.write("       <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td> </td>\r\n");
      out.write("            <td> 상품이름</td>\r\n");
      out.write("            <td> 가격</td>\r\n");
      out.write("           <td> 판매자</td>\r\n");
      out.write("            \r\n");
      out.write("         </tr>\r\n");
      out.write("      </thead>\r\n");
      out.write("      <tbody>\r\n");
      out.write("         <tr>\r\n");
      out.write("           <td><img alt=\"파리\" src=\"../resources/images/a.jpg\" width=\"150px\" height=\"100px\" /></td>\r\n");
      out.write("            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.contract_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.seller }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>   \r\n");
      out.write("        </tr>  \r\n");
      out.write("      </tbody>   \r\n");
      out.write("   </table>\r\n");
      out.write("   <br/><hr/>\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <h3>구매평: 상품의 만족도를 선택해주세요</h3>\r\n");
      out.write("    \r\n");
      out.write("   <div class=\"vote_lst\">\r\n");
      out.write("         <dl class=\"lt\">\r\n");
      out.write("         <dt id=\"topStarLabel\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/detail/txt_point_click.gif\" width=\"38\" height=\"11\" class=\"starscore_guide_txt\" alt=\"별점주기\"></dt>\r\n");
      out.write("            <dd id=\"topStarSelectbox\">\r\n");
      out.write("               <div class=\"pointSelect fl\" >\r\n");
      out.write("                     <a onclick=\"clickSelector()\" href=\"#\" class=\"default\" id=\"starScoreMenu_1\"><span class=\"star_type4\"><span id=\"topTargetMask\" class=\"mask\" style=\"width:100%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"점수선택\" class=\"starscore_star_pic\" ></span></span></a>\r\n");
      out.write("                    <ul style=\"display:none;margin:0px;padding:0px;\" id=\"pointSelectOption\">\r\n");
      out.write("                       <li><a onclick=\"clickcr(this,'10')\" href=\"#\" id=\"topStar10Select\" title=\"10점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:100%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"10점\">10점</span></span></a></li>\r\n");
      out.write("                        <li><a onclick=\"clickcr(this,'9')\" href=\"#\" id=\"topStar9Select\" title=\"9점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:90%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"9점\">9점</span></span></a></li>\r\n");
      out.write("                        <li><a onclick=\"clickcr(this,'8')\" href=\"#\" id=\"topStar8Select\" title=\"8점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:80%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"8점\">8점</span></span></a></li>\r\n");
      out.write("                        <li><a onclick=\"clickcr(this,'7')\" href=\"#\" id=\"topStar7Select\" title=\"7점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:70%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"7점\">7점</span></span></a></li>\r\n");
      out.write("                        <li><a onclick=\"clickcr(this,'6')\" href=\"#\" id=\"topStar6Select\" title=\"6점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:60%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"6점\">6점</span></span></a></li>\r\n");
      out.write("                        <li><a onclick=\"clickcr(this,'5')\" href=\"#\" id=\"topStar5Select\" title=\"5점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:50%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"5점\">5점</span></span></a></li>\r\n");
      out.write("                        <li><a onclick=\"clickcr(this,'4')\" href=\"#\" id=\"topStar4Select\" title=\"4점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:40%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"4점\">4점</span></span></a></li>\r\n");
      out.write("                        <li><a onclick=\"clickcr(this,'3')\" href=\"#\" id=\"topStar3Select\" title=\"3점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:30%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"3점\">3점</span></span></a></li>\r\n");
      out.write("                        <li><a onclick=\"clickcr(this,'2')\" href=\"#\" id=\"topStar2Select\" title=\"2점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:20%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"2점\">2점</span></span></a></li>\r\n");
      out.write("                        <li><a onclick=\"clickcr(this,'1')\" href=\"#\" id=\"topStar1Select\" title=\"1점\"><span class=\"star_type4\"><span class=\"mask\" style=\"width:10%\"><img src=\"http://static.comic.naver.net/staticImages/COMICWEB/NAVER/img/common/ico_star_n.gif\" width=\"60\" height=\"12\" alt=\"1점\">1점</span></span></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("               <!--  <a href=\"#\" class=\"btn_bx fl\" id=\"topStarScoreSubmitButton\" onclick=\"clickcr(this,'bdt.starok','','');\"  ><span>확인</span></a> -->\r\n");
      out.write("            </dd>\r\n");
      out.write("            <dd id=\"topStarText\" class=\"txt\" style=\"display:none;\"><span>참여하셨습니다.</span></dd>\r\n");
      out.write("        </dl>       \r\n");
      out.write("        \r\n");
      out.write("        <br/><br/><br/>\r\n");
      out.write("        \r\n");
      out.write("        <!-- grade와 detail값을 넘겨줌 -->\r\n");
      out.write("        <form action=\"registerReview\" method=\"post\">\r\n");
      out.write("        \t<!-- productVO의 -->\r\n");
      out.write("           <input type=\"hidden\" name=\"product_code\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("           <input type=\"hidden\" name=\"seller\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.seller}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("           \r\n");
      out.write("           <!-- reviewVO의 -->\r\n");
      out.write("           <input type=\"hidden\" name=\"grade\" id=\"grade\"/>\r\n");
      out.write("           <textarea  rows=\"4\" cols=\"60\" name=\"detail\" ></textarea> \r\n");
      out.write("           <br/>                  \r\n");
      out.write("           <input type=\"submit\" value=\"확인\"/>\r\n");
      out.write("        \r\n");
      out.write("        </form>      \r\n");
      out.write("   \r\n");
      out.write("   </div> \r\n");
      out.write("      \r\n");
      out.write("   <script>\r\n");
      out.write("         \r\n");
      out.write("    function clickSelector(){\r\n");
      out.write("       var display = $('#pointSelectOption').css('display');\r\n");
      out.write("               \r\n");
      out.write("        if(display=='none'){\r\n");
      out.write("           $('#pointSelectOption').css('display','inline-table');\r\n");
      out.write("        }else {\r\n");
      out.write("           $('#pointSelectOption').css('display','none');\r\n");
      out.write("        }\r\n");
      out.write("   }//function clickSelector()\r\n");
      out.write("            \r\n");
      out.write("   function clickcr(p,num){\r\n");
      out.write("      var wid=num*10;\r\n");
      out.write("   \r\n");
      out.write("      $('#pointSelectOption').css('display','none');//drop-down-list 접는다\r\n");
      out.write("      $('#topTargetMask').css('width', wid+'%');\r\n");
      out.write("      \r\n");
      out.write("      $('#grade').val(num);\r\n");
      out.write("   }\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
