/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.43
 * Generated at: 2017-11-18 05:22:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Study/lab_web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Auction/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1496842997460L));
    _jspx_dependants.put("/WEB-INF/views/product/header.jspf", Long.valueOf(1510499954744L));
    _jspx_dependants.put("jar:file:/C:/Study/lab_web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Auction/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("      <!-- jQuery CDN 포함: 라이브러리 포함  -->\r\n");
      out.write("      <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <title>Auction_Main</title>\r\n");
      out.write("\r\n");
      out.write("    <!--  Bootstrap 최신 버전의 CSS 파일들을 링크 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style media=\"screen\">\r\n");
      out.write("      .main{\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        min-width: 1200px;\r\n");
      out.write("        height: 1000px;\r\n");
      out.write("        /*background-color:#ffa;*/\r\n");
      out.write("        /*\r\n");
      out.write("        찐주황:  #F15A22;\r\n");
      out.write("        연주황: #F58220\r\n");
      out.write("        하늘: #00ADF0\r\n");
      out.write("        */\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("      .body1{\r\n");
      out.write("\r\n");
      out.write("        width: 965px;\r\n");
      out.write("        height:410px;\r\n");
      out.write("\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        background-color: #000;\r\n");
      out.write("        /*url로 줄때는 또 슬래쉬로 줘야함 \\ 이거 안됨 .. */\r\n");
      out.write("        /*background-image: url(\"resources/images/food/김장3.jpg\");*/\r\n");
      out.write("        /*background-image: url(\"resources/images/food/고흥군특산물.jpg\");*/\r\n");
      out.write("        /*background-image: url(\"resources/images/food/한돈.jpg\");*/\r\n");
      out.write("        /*background-image: url(\"resources/images/food/호두.jpg\");*/\r\n");
      out.write("        background-image: url(\"resources/images/food/수산물.jpg\"); \r\n");
      out.write("        /*background-image: url(\"resources/images/food/육류.jpg\");*/\r\n");
      out.write("        position: relative;\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .search_form{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        background-color: #F15A22;\r\n");
      out.write("\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 410px;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .body2{\r\n");
      out.write("        margin-top: 120px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("   <link rel=\"stylesheet\"\r\n");
      out.write("  href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" />\r\n");
      out.write(" <style>\r\n");
      out.write("      .top1{\r\n");
      out.write("        background-color: #00ADF0;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("        padding-top: 10px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .top2{\r\n");
      out.write("        background-color: #F58220 ;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        padding-top: 5px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .top3{\r\n");
      out.write("        background-color: #F15A22;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .text{\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        /* 세로 가운데 정렬도 해야해 */\r\n");
      out.write("\r\n");
      out.write("        padding-left: 30px;\r\n");
      out.write("        padding-right: 30px;\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("      .breadcrumb{\r\n");
      out.write("        background-color: transparent;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        padding: 8px 15px;\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #tricycle{\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("        margin-left: 30px;\r\n");
      out.write("        margin-right: 0px; /*옆에 글씨 적으려고*/\r\n");
      out.write("        height:60px;\r\n");
      out.write("        vertical-align: top;\r\n");
      out.write("        border:0px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .breadcrumb2{\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("      }\r\n");
      out.write("      .breadcrumb2 li{\r\n");
      out.write("        float: left;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("      }\r\n");
      out.write("      .breadcrumb2:after{\r\n");
      out.write("        content:'';\r\n");
      out.write("        clear:both;\r\n");
      out.write("      }\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header id=\"top\">\r\n");
      out.write("\r\n");
      out.write(" <!-- <div class=\"top1\">\r\n");
      out.write("        <div class=\"text little\" >\r\n");
      out.write("          중고거래 가능한 옥션 장터입니다!\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div> -->\r\n");
      out.write("      <div class=\"top2\">\r\n");
      out.write("        <ul class=\"breadcrumb\">\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/user/login\">로그인</a></li>\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/user/registerUser\">회원가입</a></li>\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/user/cart\">장바구니</a></li>\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/product/registerProduct\">제품등록</a></li>\r\n");
      out.write("          <li><a class=\"text\" href=\"/auc/user/mypage\">마이옥션</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"top3\">\r\n");
      out.write("        <img id=\"tricycle\" src=\"http://localhost:8181\\auc\\resources\\images\\tricycle.png\" alt=\"세모동그라미\">\r\n");
      out.write("        <span class=\"text\"\r\n");
      out.write("          style=\"margin-left:0px; padding-left:0px; font-size:40px;\">UCTION  장터</span>\r\n");
      out.write("          <!--여기서 span에 margin-left 스타일 먹이면 왜 안먹을까 20px; 100px;등-->\r\n");
      out.write("          \r\n");
      out.write("         <ul class=\"breadcrumb2\">\r\n");
      out.write("          \r\n");
      out.write("          <li><h4><a class=\"text\" href=\"product/productList?category=fresh\" \r\n");
      out.write("          \t\t\tonmouseover=\"mouseover_header(this)\" onmouseout=\"mouseout_header(this)\">\r\n");
      out.write("            \t\t쌀/과일/농수축산물</a></h4></li>\r\n");
      out.write("          \r\n");
      out.write("          <li><h4><a class=\"text\" href=\"product/productList?category=drink\"\r\n");
      out.write("          \t\t\tonmouseover=\"mouseover_header(this)\" onmouseout=\"mouseout_header(this)\">\r\n");
      out.write("            \t\t커피/음료</a></h4></li>\r\n");
      out.write("          \r\n");
      out.write("          <li><h4><a class=\"text\" href=\"product/productList?category=healthy\"\r\n");
      out.write("         \t\t\tonmouseover=\"mouseover_header(this)\" onmouseout=\"mouseout_header(this)\">\r\n");
      out.write("            \t\t건강/다이어트</a></h4></li>\r\n");
      out.write("          \r\n");
      out.write("          <li><h4><a class=\"text\" href=\"product/productList?category=instant\" \r\n");
      out.write("          \t\t\tonmouseover=\"mouseover_header(this)\" onmouseout=\"mouseout_header(this)\">\r\n");
      out.write("           \t\t\t 즉석/가공식품</a></h4></li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    function mouseover_header(obj){\r\n");
      out.write("\r\n");
      out.write("      obj.style.color=\"#000\";\r\n");
      out.write("    }\r\n");
      out.write("    function mouseout_header(obj){\r\n");
      out.write("\r\n");
      out.write("      obj.style.color=\"#fff\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("        // 이렇게 하는게 안되는 이유!!\r\n");
      out.write("        // (넘나재밌는거) 등록된 onmouseover가 불렸을때 category[length]가 불려버림!없는 객체ㅇㅇ\r\n");
      out.write("\r\n");
      out.write("        // for(i=0;i<category.length;i++){\r\n");
      out.write("        //   category[i].onmouseover=\r\n");
      out.write("        //     function(){\r\n");
      out.write("        //       category[i].style.color=\"#000\";\r\n");
      out.write("        //     };\r\n");
      out.write("        //   category[i].onmouseout=\r\n");
      out.write("        //     function(){\r\n");
      out.write("        //       category[i].style.color=\"#fff\";\r\n");
      out.write("        //   };\r\n");
      out.write("        // }\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("      <div class=\"body1\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"search_form\">\r\n");
      out.write("        <!--검색 form! -->\r\n");
      out.write("        <form id=\"search\" action=\"product/productList\">\r\n");
      out.write("\r\n");
      out.write("                             <div class=\"block1\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                   <label for=\"user_id\" class=\"col-sm-2 control-label lable-title\">\r\n");
      out.write("\r\n");
      out.write("                                   <select id = \"category\" name =\"category\" style=\"width:150px; height:33px; border-width:1px; border-radius:5px; border-color:#800000; background-color: #ffffff;\r\n");
      out.write("                                       box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);\">\r\n");
      out.write("                                     <option value=\"all\" >========전체=======</option>\r\n");
      out.write("                                      <option value=\"fresh\" >쌀/과일/농수축산물</option>\r\n");
      out.write("                                   <option value=\"drink\" >커피/음료</option>\r\n");
      out.write("                                     <option value=\"healthy\" >건강/다이어트</option>\r\n");
      out.write("                                   <option value=\"instant\" >즉석/가공식품</option>\r\n");
      out.write("                              </select></label>\r\n");
      out.write("                                   <div class=\"col-sm-8\">\r\n");
      out.write("                                      <input type=\"text\" class=\"form-control\" id=\"usrId\" name=\"name\" placeholder=\"상품이름을 입력하세요\" value=\"\" required>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                   <button type=\"submit\" class=\"btn btn-primary btn-block btn-login\"  id=\"login_btn\" style=\"width:150px; background-color: #800000; border-color: #800000;\">검색하기</button>\r\n");
      out.write("\r\n");
      out.write("                                 </div>\r\n");
      out.write("\r\n");
      out.write("                               </div>\r\n");
      out.write("         </form>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"body2\">\r\n");
      out.write("        <img src=\"http://static.ssgcdn.com/ui/ssg/img/common/h3_tit_06.gif\" alt=\"Category Best\">\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
